language: go

go:
  - 1.10.4

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script: make test
